[project]
name = "bilibili-live-stream-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.7.5",
    "pillow>=11.2.1",
    "pyside6>=6.9.0",
    "qrcode>=8.2",
    "requests>=2.32.3",
]
